name: Keep Streamlit Apps Alive

on:
  schedule:
    - cron: '38 18 * * *'

  workflow_dispatch:

jobs:
  ping-apps:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to app
        run: curl -s -o /dev/null -w "%{http_code}\n" https://projetodashboardgestaodasaguasufsc.streamlit.app/
