name: run schedule.py

on:
  schedule:
    - cron: '14 19 * * *'    #runs at 00:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: execute py script # run file
        run: |
          schedule.py
