name: py

on:
  schedule:
    - cron: "54 18 * * *"    #runs at 00:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: execute py script # run file
        run: |
          schedule.py
