name: run schedule py

on:
  schedule:
    - cron: '*/2 * * * *'    #runs at 00:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Install the Python version needed

     

      # Step 3: Run py
      - name: execute py script # run file
        run: |
          python schedule.py
